# Generated by Django 5.2.17 on 2026-08-08 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('telefono', models.CharField(max_length=15)),
                ('autoriza_tratamiento_datos', models.BooleanField(default=False)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='matriculas.area')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=12)),
                ('horario', models.CharField(max_length=60)),
                ('salon', models.CharField(max_length=40)),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='matriculas.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('director', 'Director de escuela'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], max_length=15)),
                ('nombre_completo', models.CharField(max_length=90)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('foto_perfil', models.ImageField(upload_to='fotos_perfil/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaDemografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro'), ('ns', 'Prefiero no responder')], max_length=2)),
                ('barrio', models.CharField(max_length=60)),
                ('estrato', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('nivel_educativo', models.CharField(max_length=40)),
                ('ocupacion', models.CharField(max_length=40)),
                ('grupo_etnico', models.CharField(blank=True, max_length=40)),
                ('discapacidad', models.CharField(blank=True, max_length=80)),
                ('autoriza_tratamiento_datos', models.BooleanField(default=False)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='matriculas.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='DatosEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=15, unique=True)),
                ('copia_documento', models.FileField(upload_to='documentos/')),
                ('acudiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='matriculas.acudiente')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_estudiante', to='matriculas.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.PROTECT, related_name='cursos_dictados', to='matriculas.perfil'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('retirada', 'Retirada')], default='activa', max_length=10)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='matriculas.grupo')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='matriculas.perfil')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='matriculas.periodo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('curso', 'nivel'), name='un_nivel_por_curso'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('estudiante', 'grupo', 'periodo'), name='unica_matricula_por_periodo'),
        ),
    ]
