# Generated by Django 5.2.17 on 2026-08-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acudiente',
            options={'verbose_name': 'Acudiente', 'verbose_name_plural': 'Acudientes'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='datosestudiante',
            options={'verbose_name': 'Datos del estudiante', 'verbose_name_plural': 'Datos de estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='encuestademografica',
            options={'verbose_name': 'Encuesta demográfica', 'verbose_name_plural': 'Encuestas demográficas'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='autoriza_tratamiento_datos',
            field=models.BooleanField(default=False, verbose_name='autoriza tratamiento de datos'),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de autorización'),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='copia_documento',
            field=models.FileField(upload_to='documentos/', verbose_name='copia del documento'),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='documento_identidad',
            field=models.CharField(max_length=15, unique=True, verbose_name='documento de identidad'),
        ),
        migrations.AlterField(
            model_name='encuestademografica',
            name='autoriza_tratamiento_datos',
            field=models.BooleanField(default=False, verbose_name='autoriza tratamiento de datos'),
        ),
        migrations.AlterField(
            model_name='encuestademografica',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de autorización'),
        ),
        migrations.AlterField(
            model_name='encuestademografica',
            name='genero',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), ('o', 'Otro'), ('ns', 'Prefiero no responder')], max_length=2, verbose_name='género'),
        ),
        migrations.AlterField(
            model_name='encuestademografica',
            name='grupo_etnico',
            field=models.CharField(blank=True, max_length=40, verbose_name='grupo étnico'),
        ),
        migrations.AlterField(
            model_name='encuestademografica',
            name='nivel_educativo',
            field=models.CharField(max_length=40, verbose_name='nivel educativo'),
        ),
        migrations.AlterField(
            model_name='encuestademografica',
            name='ocupacion',
            field=models.CharField(max_length=40, verbose_name='ocupación'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='cupo_maximo',
            field=models.PositiveIntegerField(verbose_name='cupo máximo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='salon',
            field=models.CharField(max_length=40, verbose_name='salón'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(upload_to='fotos_perfil/', verbose_name='foto de perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre_completo',
            field=models.CharField(max_length=90, verbose_name='nombre completo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_fin',
            field=models.DateField(verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
    ]
