# Generated by Django 5.2.17 on 2026-08-09 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_alter_acudiente_options_alter_area_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Promotoría',
                'verbose_name_plural': 'Promotorías',
            },
        ),
        migrations.RemoveConstraint(
            model_name='grupo',
            name='un_nivel_por_curso',
        ),
        migrations.RemoveConstraint(
            model_name='matricula',
            name='unica_matricula_por_periodo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='area',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='curso',
        ),
        migrations.AlterField(
            model_name='matricula',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Lo asigna el profesor al dividir a los estudiantes matriculados.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='matriculas.grupo'),
        ),
        migrations.AddField(
            model_name='promotoria',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotorias', to='matriculas.area'),
        ),
        migrations.AddField(
            model_name='promotoria',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.PROTECT, related_name='promotorias_dictadas', to='matriculas.perfil'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='promotoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='matriculas.promotoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='promotoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='matriculas.promotoria'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('promotoria', 'nivel'), name='un_nivel_por_promotoria'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('estudiante', 'promotoria', 'periodo'), name='unica_matricula_por_periodo'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
