# Generated by Django 5.2.17 on 2026-08-09 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_promotoria_remove_curso_area_remove_curso_profesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotoria',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotorias_dictadas', to='matriculas.perfil'),
        ),
    ]
