# Generated by Django 5.2.17 on 2026-08-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0004_alter_promotoria_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('director', 'Director de escuela'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], help_text='En blanco = cuenta creada por autorregistro, pendiente de que un director/administrador le asigne rol.', max_length=15),
        ),
    ]
