# Generated by Django 5.2.17 on 2026-08-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0005_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('activa', 'Activa'), ('retirada', 'Retirada')], default='pendiente', max_length=10),
        ),
    ]
