# Generated by Django 5.2.17 on 2026-08-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0006_alter_matricula_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='copia_documento',
            field=models.FileField(blank=True, upload_to='documentos/', verbose_name='copia del documento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='fotos_perfil/', verbose_name='foto de perfil'),
        ),
    ]
