# Generated by Django 5.2.17 on 2026-08-10 15:42

from django.db import migrations, models


def repartir_ranuras(apps, schema_editor):
    """Numera las matrículas ya existentes: 1, 2, ... por estudiante y periodo.

    El campo nace con default=1, así que sin este reparto dos matrículas sin
    retirar del mismo estudiante chocarían contra el índice único que se crea
    justo después. Las retiradas quedan fuera del índice y conservan su valor.
    """
    Matricula = apps.get_model("matriculas", "Matricula")
    vistas = {}
    consulta = (
        Matricula.objects.exclude(estado="retirada")
        .order_by("estudiante_id", "periodo_id", "fecha", "id")
    )
    for matricula in consulta:
        clave = (matricula.estudiante_id, matricula.periodo_id)
        siguiente = vistas.get(clave, 0) + 1
        vistas[clave] = siguiente
        if matricula.ranura != siguiente:
            matricula.ranura = siguiente
            matricula.save(update_fields=["ranura"])


def deshacer_ranuras(apps, schema_editor):
    """Vuelta atrás: el campo desaparece con el AddField, no hay nada que restaurar."""


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0007_alter_datosestudiante_copia_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='ranura',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cuál de los cupos del estudiante ocupa esta matrícula en el periodo (1 o 2). La asigna el sistema; es lo que permite que la base de datos misma impida un tercer cupo.'),
        ),
        migrations.RunPython(repartir_ranuras, deshacer_ranuras),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.CheckConstraint(condition=models.Q(('ranura__gte', 1), ('ranura__lte', 2)), name='ranura_valida'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'retirada'), _negated=True), fields=('estudiante', 'periodo', 'ranura'), name='max_dos_promotorias_por_periodo'),
        ),
    ]
