# Generated by Django 5.2.17 on 2026-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0008_limite_dos_promotorias'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='matricula',
            name='max_dos_promotorias_por_periodo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'retirada'), _negated=True), fields=('estudiante', 'periodo', 'ranura'), name='max_dos_promotorias_por_periodo', violation_error_message='Un estudiante puede estar en un máximo de 2 promotorías por periodo, y este ya tiene ese cupo ocupado. Retira una matrícula antes de agregar otra.'),
        ),
    ]
