# Generated by Django 5.2.17 on 2026-08-10 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0009_mensaje_limite_promotorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoPromotoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_maximo', models.PositiveIntegerField(verbose_name='cupo máximo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos_promotoria', to='matriculas.periodo')),
                ('promotoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='matriculas.promotoria')),
            ],
            options={
                'verbose_name': 'Cupo de promotoría',
                'verbose_name_plural': 'Cupos de promotoría',
                'constraints': [models.UniqueConstraint(fields=('promotoria', 'periodo'), name='un_cupo_por_promotoria_y_periodo')],
            },
        ),
    ]
