# Generated by Django 5.2.17 on 2026-08-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0011_trigger_cupo_promotoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='matriculas_abiertas',
            field=models.BooleanField(default=False, help_text='Mientras esté cerrado, nadie puede inscribirse ni renovar en este periodo.', verbose_name='matrículas abiertas'),
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaccion_general', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='satisfacción general')),
                ('calificacion_profesor', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='acompañamiento del profesor')),
                ('horario_funciono', models.BooleanField(verbose_name='el horario le funcionó')),
                ('recomendaria', models.BooleanField(verbose_name='recomendaría la promotoría')),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_satisfaccion', to='matriculas.perfil')),
                ('periodo', models.ForeignKey(help_text='El periodo que el estudiante evalúa, no aquel al que se renueva.', on_delete=django.db.models.deletion.PROTECT, related_name='encuestas_satisfaccion', to='matriculas.periodo')),
            ],
            options={
                'verbose_name': 'Encuesta de satisfacción',
                'verbose_name_plural': 'Encuestas de satisfacción',
                'constraints': [models.UniqueConstraint(fields=('perfil', 'periodo'), name='una_encuesta_satisfaccion_por_periodo', violation_error_message='Ya respondiste la encuesta de satisfacción de ese periodo.')],
            },
        ),
    ]
