# Generated by Django 5.2.17 on 2026-08-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0012_renovacion_y_ventana_matriculas'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='periodo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='un_solo_periodo_activo', violation_error_message='Ya hay un periodo en curso. Cambia cuál es el periodo en curso desde Gestión → Iniciar / finalizar matrículas.'),
        ),
    ]
