# Generated by Django 5.2.17 on 2026-08-10 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0013_un_solo_periodo_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='Casa de la Cultura', help_text='Aparece en la cabecera, los títulos de página y el admin de Django.', max_length=80, verbose_name='nombre de la institución')),
                ('logo', models.ImageField(blank=True, help_text='Si se deja vacío se usa el logo que trae el proyecto por defecto.', upload_to='institucion/')),
                ('color_acento', models.CharField(default='#0a7a59', help_text='Único color de marca del sistema: botones, enlaces, foco y mensajes de éxito. Los tonos hover y de fondo se derivan de este automáticamente.', max_length=7, validators=[django.core.validators.RegexValidator(message='Escribe el color en formato hexadecimal de 6 dígitos, por ejemplo #0a7a59.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='color de acento')),
            ],
            options={
                'verbose_name': 'Configuración de la institución',
                'verbose_name_plural': 'Configuración de la institución',
            },
        ),
    ]
