# Generated by Django 5.2.17 on 2026-08-11 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0014_configuracion_institucion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matricula',
            name='ranura_valida',
        ),
        migrations.RemoveConstraint(
            model_name='matricula',
            name='max_dos_promotorias_por_periodo',
        ),
        migrations.AddField(
            model_name='configuracioninstitucion',
            name='limite_promotorias_por_periodo',
            field=models.PositiveSmallIntegerField(default=2, help_text='Cuántas promotorías puede cursar un mismo estudiante en un periodo. Cuentan las matrículas pendientes y las activas; las retiradas liberan cupo. Bajarlo no retira ni rompe las matrículas que ya existen: solo impide pedir más a quien ya esté en el nuevo límite o por encima.', validators=[django.core.validators.MinValueValidator(1, message='El límite tiene que ser de al menos 1 promotoría por periodo.'), django.core.validators.MaxValueValidator(6, message='El máximo que admite la base de datos es 6 promotorías por periodo. Subir de ahí exige una migración.')], verbose_name='promotorías por estudiante y periodo'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='ranura',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cuál de los cupos del estudiante ocupa esta matrícula en el periodo. La asigna el sistema; es lo que permite que la base de datos misma impida que dos matrículas compartan cupo.'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.CheckConstraint(condition=models.Q(('ranura__gte', 1), ('ranura__lte', 6)), name='ranura_valida'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'retirada'), _negated=True), fields=('estudiante', 'periodo', 'ranura'), name='una_matricula_por_ranura_y_periodo', violation_error_message='Este estudiante ya tiene ocupado su cupo de promotorías para el periodo. Retira una matrícula antes de agregar otra.'),
        ),
    ]
