# Generated by Django 5.2.17 on 2026-08-15 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0020_alter_promotoria_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Cómo lo verá el estudiante. Por ejemplo: «Certificado de EPS».', max_length=60)),
                ('descripcion', models.CharField(blank=True, help_text='Aclaración opcional: vigencia, formato, dónde conseguirlo.', max_length=200, verbose_name='descripción')),
                ('obligatorio', models.BooleanField(default=True, help_text='Si no es obligatorio se le pide igual, pero su ausencia no marca la matrícula como incompleta.')),
                ('activo', models.BooleanField(default=True, help_text='Desactívalo para dejar de pedirlo sin borrar lo ya entregado.')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Menor primero. Con el mismo número manda el nombre.')),
            ],
            options={
                'verbose_name': 'Documento requerido',
                'verbose_name_plural': 'Documentos requeridos',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='un_documento_por_nombre')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('subido', models.DateTimeField(auto_now=True)),
                ('datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='matriculas.datosestudiante')),
                ('requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='matriculas.documentorequerido')),
            ],
            options={
                'verbose_name': 'Documento de estudiante',
                'verbose_name_plural': 'Documentos de estudiantes',
                'constraints': [models.UniqueConstraint(fields=('datos', 'requerido'), name='un_archivo_por_documento_y_estudiante')],
            },
        ),
    ]
