# Generated by Django 5.2.17 on 2026-08-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0021_documentos_requeridos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucion',
            name='promotorias_visibles_para_estudiantes',
            field=models.BooleanField(default=True, help_text='Con esto apagado, el estudiante no ve la pantalla para matricularse por su cuenta y solo consulta lo que ya tiene. Sirve para las instituciones que inscriben en ventanilla: el personal matricula desde Gestión y la pantalla pública solo confundiría. No afecta a las matrículas ya hechas.', verbose_name='los estudiantes ven el catálogo de promotorías'),
        ),
    ]
